version: '3'
services:

  installer:
    container_name: senzing-installer
    environment:
#     See https://github.com/Senzing/docker-installer#configuration
      SENZING_DEPLOY_ETC_OPT_SENZING: true
      SENZING_DEPLOY_OPT_MICROSOFT: true
    image: senzing/installer:${SENZING_DOCKER_IMAGE_VERSION_SENZING_INSTALLER:-latest}
    networks:
      - senzing
    read_only: true
    restart: on-failure
    volumes:
      - ${SENZING_OPT_SENZING_DIR:-/opt/senzing}:/opt/senzing
      - ${SENZING_ETC_DIR:-/etc/opt/senzing}:/etc/opt/senzing
      - ${SENZING_OPT_MICROSOFT_DIR:-/opt/microsoft}:/opt/microsoft

networks:
  senzing:
    external:
      name: ${SENZING_DOCKER_NETWORK:-senzing-network}
