name: docker-build-container.yaml

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image
        uses: Senzing/github-action-docker-buildx-build@latest
        with:
          build-options: |
            --build-arg SENZING_ACCEPT_EULA=I_ACCEPT_THE_SENZING_EULA
            --build-arg ACCEPT_EULA=Y
          image-repository: senzing/installer
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
